# Generated by Django 4.1.5 on 2023-01-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_description_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Details about this product...'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(default='Cost...'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='Summary of description...'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(default='Title of the product...'),
        ),
    ]
