CREATE TABLE DRUG(
AMOUNT NUMBER(20),
INTAKE VARCHAR(20),
COST NUMBER(20));

CREATE TABLE SERVICE(
SERV_TYPE VARCHAR(30),
UNITCOST NUMBER(20),
PRIMARY KEY(SERV_TYPE));

CREATE TABLE PEDIATRIC(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE GENERAL(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE PRACTICE(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE XRAY(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE SPECIALIST(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE LABORATORY(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE THERAPY(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE INVOICE(
INVOICEID VARCHAR(20),
SERV_TYPE# NUMBER(20),
COST NUMBER(20),
PRIMARY KEY(INVOICEID));

CREATE TABLE TREATMENT(
INVOICEID VARCHAR(20),
FOREIGN KEY(INVOICEID) REFERENCES INVOICE(INVOICEID));
