--RAUSHAWN CODE
CREATE TABLE DRUG(
AMOUNT NUMBER(20),
INTAKE VARCHAR(20),
COST NUMBER(20));

CREATE TABLE SERVICE(
SERV_TYPE VARCHAR(30),
UNITCOST NUMBER(20),
PRIMARY KEY(SERV_TYPE));

CREATE TABLE PEDIATRIC(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE GENERAL(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE PRACTICE(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE XRAY(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE SPECIALIST(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE LABORATORY(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE THERAPY(
SERV_TYPE VARCHAR(30),
FOREIGN KEY(SERV_TYPE) REFERENCES SERVICE(SERV_TYPE));

CREATE TABLE INVOICE(
INVOICEID VARCHAR(20),
SERV_TYPE# NUMBER(20),
COST NUMBER(20),
PRIMARY KEY(INVOICEID));

CREATE TABLE TREATMENT(
INVOICEID VARCHAR(20),
FOREIGN KEY(INVOICEID) REFERENCES INVOICE(INVOICEID));


--AARON CODE

--Patient Table sequence
CREATE SEQUENCE pat_num
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;
--Patient Table
CREATE TABLE Patient(
    pat_num NUMBER PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    DOB date NOT NULL,
    allergies VARCHAR(50) NOT NULL,
    bloodType VARCHAR(2) NOT NULL,
    address VARCHAR(100) NOT NULL
);

--Appointment Table sequence
CREATE SEQUENCE appID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;
--Appointment Bridge Table
CREATE TABLE Appointment (
    appID NUMBER PRIMARY KEY,
    pat_num NUMBER,
    doctor_ID NUMBER,
    time TIMESTAMP,
    particular VARCHAR(100),
    CSR VARCHAR(20),
    FOREIGN KEY(pat_num) REFERENCES Patient(pat_num),
    FOREIGN KEY(pat_num) REFERENCES Patient(pat_num)
);

--STAFF Table sequence
CREATE SEQUENCE staffID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;
--STAFF Table <<SUPER CLASS>>
CREATE TABLE STAFF(
    ID NUMBER NOT NULL PRIMARY KEY,
    name VARCHAR(20),
    type VARCHAR(13),
    address VARCHAR(50),
    department VARCHAR(20),
    appID NUMBER NOT NULL,
    FOREIGN KEY(appID) REFERENCES Appointment(appID)
);

--Doctor Table <<SUB CLASS OF STAFF>>
CREATE TABLE DOCTOR(
    staffID NUMBER PRIMARY KEY NOT NULL,
    FOREIGN KEY(staffID) REFERENCES STAFF(staffID)
);

--Nurse Table <<SUB CLASS OF STAFF>>
CREATE TABLE NURSE(
    staffID NUMBER PRIMARY KEY NOT NULL,
    FOREIGN KEY(staffID) REFERENCES STAFF(staffID)
);

--Technician Table <<SUB CLASS OF STAFF AND SUPER CLASS OF LAB AND X-RAY>> 
CREATE TABLE Technician(
    staffID NUMBER NOT NULL,
    techID NUMBER NOT NULL,
    FOREIGN KEY(staffID) REFERENCES STAFF(staffID),
    PRIMARY KEY(staffID, techID)
);

CREATE TABLE Lab(
    staffID NUMBER NOT NULL,
    techID NUMBER NOT NULL,
    FOREIGN KEY(techID) REFERENCES STAFF(techID),
    FOREIGN KEY(staffID) REFERENCES STAFF(staffID)
);

CREATE TABLE XRay(
    staffID NUMBER NOT NULL,
    techID NUMBER NOT NULL,
    FOREIGN KEY(techID) REFERENCES STAFF(techID),
    FOREIGN KEY(staffID) REFERENCES STAFF(staffID)
);


--Therapist Table <<SUB CLASS OF STAFF>>
CREATE TABLE Therapist(
    staffID NUMBER PRIMARY KEY NOT NULL,
    FOREIGN KEY(staffID) REFERENCES STAFF(staffID)
);

--CSR Table <<SUB CLASS OF STAFF>>
CREATE TABLE CSR(
    staffID NUMBER PRIMARY KEY NOT NULL,
    FOREIGN KEY(staffID) REFERENCES STAFF(staffID)
);